services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                MYSQL_CLIENT: mariadb-client
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - 'tmpfiles:/tmp'
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mariadb
            - chromium
    chromium:
        image: zenika/alpine-chrome:latest
        command: [ chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
        cap_add:
            - SYS_ADMIN
        ports:
            - '9222:9222'
        volumes:
            - tmpfiles:/tmp
        networks:
            sail:
                ipv4_address: 172.22.0.100
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
    ngrok:
        image: 'ngrok/ngrok:alpine'
        environment:
            NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
        command: 'http laravel.test:80 --domain=honestly-optimum-seagull.ngrok-free.app --host-header=rewrite'
        ports:
            - '4040:4040'
        networks:
            - sail
        depends_on:
            - laravel.test
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9001}:9001'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: 'minio'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'minio:/data/minio'
        networks:
            - sail
        command: minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT:-8900}" --address ":${FORWARD_MINIO_PORT:-9001}"
    gotenberg:
        image: gotenberg/gotenberg:7
        ports:
            - "3000:3000"
        networks:
            - sail
        volumes:
            - tmpfiles:/tmp

networks:
    sail:
        ipam:
            driver: default
            config:
                - subnet: "172.22.0.0/24"
volumes:
    tmpfiles:
        driver: local
    sail-mariadb:
        driver: local
    minio:
        driver: local
